
 
stages:
  - test
 
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
 
test:
  stage: test
  allow_failure: true
  tags: 
    - toto
 
# Run the tests  
  script:
    - mvn $MAVEN_OPTS clean package
    - mvn compile test
 
# Store artifacts
 
  artifacts:
    when: always
    reports:
      junit: target/**/TEST-*.xml